apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
  namespace: mysql-ns
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: mysql-init
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              sleep 10
              mysql -h mysql-0.mysql-service.mysql-ns.svc.cluster.local -u root -prootpassword testdb <<EOF
              CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                username VARCHAR(50) NOT NULL UNIQUE,
                first_name VARCHAR(50) NOT NULL,
                last_name VARCHAR(50) DEFAULT NULL,
                email VARCHAR(100) NOT NULL
              );

              INSERT IGNORE INTO users (username, first_name, last_name, email) VALUES
                ('alice', 'Alice', NULL, 'alice@example.com'),
                ('bob.smith', 'Bob', 'Smith', 'bob@example.com'),
                ('charlie.brown', 'Charlie', 'Brown', 'charlie@example.com'),
                ('diana.ross', 'Diana', 'Ross', 'diana@example.com'),
                ('eve', 'Eve', NULL, 'eve@example.com');
              EOF
              echo "Database initialized successfully!"
      restartPolicy: OnFailure

