apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-ns
type: Opaque
data:
  # rootpassword (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # myuser: mypassword (base64 encoded)
  mysql-user: bXl1c2Vy
  mysql-password: bXlwYXNzd29yZA==
